[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
bytemuck = "1.23.2"
cgmath = "0.18.0"
math = { path = "crates/math" }
serde = { version = "1.0.226", features = ["derive"] }

[workspace.lints]
